---
grafana_version: "10.2.3"
grafana_port: 3000
grafana_user: grafana
grafana_group: grafana
grafana_config_dir: /etc/grafana
grafana_data_dir: /var/lib/grafana
grafana_log_dir: /var/log/grafana
grafana_admin_user: admin
grafana_admin_password: admin123
