---
- name: Install Grafana dependencies
  apt:
    name:
      - adduser
      - libfontconfig1
    state: present

- name: Add Grafana GPG key
  apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- name: Add Grafana repository
  apt_repository:
    repo: "deb https://apt.grafana.com stable main"
    state: present

- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Create Grafana directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: '0755'
  loop:
    - "{{ grafana_data_dir }}"
    - "{{ grafana_log_dir }}"
    - "{{ grafana_data_dir }}/dashboards"
    - "{{ grafana_data_dir }}/plugins"

- name: Configure Grafana
  template:
    src: grafana.ini.j2
    dest: "{{ grafana_config_dir }}/grafana.ini"
    owner: root
    group: "{{ grafana_group }}"
    mode: '0640'
  notify: restart grafana

- name: Create Grafana datasource configuration
  template:
    src: datasources.yml.j2
    dest: "{{ grafana_config_dir }}/provisioning/datasources/datasources.yml"
    owner: root
    group: "{{ grafana_group }}"
    mode: '0644'
  notify: restart grafana

# - name: Create Grafana dashboard configuration
#   template:
#     src: dashboards.yml.j2
#     dest: "{{ grafana_config_dir }}/provisioning/dashboards/dashboards.yml"
#     owner: root
#     group: "{{ grafana_group }}"
#     mode: '0644'
#   notify: restart grafana

# - name: Copy Node Exporter dashboard
#   template:
#     src: node-exporter-dashboard.json.j2
#     dest: "{{ grafana_data_dir }}/dashboards/node-exporter-dashboard.json"
#     owner: "{{ grafana_user }}"
#     group: "{{ grafana_group }}"
#     mode: '0644'

- name: Start and enable Grafana service
  systemd:
    name: grafana-server
    state: started
    enabled: yes
    daemon_reload: yes

- name: Wait for Grafana to start
  wait_for:
    port: "{{ grafana_port }}"
    host: "{{ ansible_host }}"
    delay: 10
    timeout: 60

- name: Verify Grafana is running
  uri:
    url: "http://localhost:{{ grafana_port }}/api/health"
    method: GET
    timeout: 10
  register: grafana_check
  retries: 3
  delay: 5