---
# - name: Deploy Private Ethereum Network with Monitoring
#   hosts: localhost
#   gather_facts: false
#   tasks:
#     - name: Display deployment information
#       debug:
#         msg: |
#           Starting deployment of Private Ethereum Network
#           Geth RPC Endpoint: {{ geth_rpc_endpoint }}
#           Grafana URL: http://54.169.122.189:3000
#           Prometheus URL: http://10.0.2.70:9090 (internal)

- name: Setup Geth Nodes
  hosts: geth_nodes
  become: yes
  vars:
    geth_nodes:
      - { ip: "10.0.1.162", id: 1 }
      - { ip: "10.0.1.90", id: 2 }
      - { ip: "10.0.3.21", id: 3 }
    geth_p2p_port: 30303
  serial: 1
  roles:
    - node_exporter
    - geth_node

  post_tasks:
    - name: Wait for Geth to be ready
      wait_for:
        port: "{{ geth_rpc_port }}"
        host: "{{ ansible_host }}"
        delay: 10
        timeout: 60

- name: Setup Monitoring Infrastructure
  hosts: monitoring
  become: yes
  vars:
    node_exporter_port: 9100
    geth_nodes:
      - { ip: "10.0.1.162", id: 1 }
      - { ip: "10.0.1.90", id: 2 }
      - { ip: "10.0.3.21", id: 3 }
  roles:
    - prometheus_server
    - grafana_server
