all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_python_interpreter: /usr/bin/python3
    bastion_host: 47.129.36.151
    
geth_nodes:
  hosts:
    geth-node-1:
      ansible_host: 10.0.1.162
      geth_node_id: 1
      enode_port: 30303
      rpc_port: 8545
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/runner/.ssh/ethereum-devops-ssh-private-key.pem
      ansible_ssh_common_args: >-
        -o ProxyCommand="ssh -W %h:%p -o StrictHostKeyChecking=no -i /home/runner/.ssh/ethereum-devops-ssh-private-key.pem ubuntu@47.129.36.151"
    geth-node-2:
      ansible_host: 10.0.3.21
      geth_node_id: 2
      enode_port: 30303
      rpc_port: 8545
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/runner/.ssh/ethereum-devops-ssh-private-key.pem
      ansible_ssh_common_args: >-
        -o ProxyCommand="ssh -W %h:%p -o StrictHostKeyChecking=no -i /home/runner/.ssh/ethereum-devops-ssh-private-key.pem ubuntu@47.129.36.151"
    geth-node-3:
      ansible_host: 10.0.1.90
      geth_node_id: 3
      enode_port: 30303
      rpc_port: 8545
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/runner/.ssh/ethereum-devops-ssh-private-key.pem
      ansible_ssh_common_args: >-
        -o ProxyCommand="ssh -W %h:%p -o StrictHostKeyChecking=no -i /home/runner/.ssh/ethereum-devops-ssh-private-key.pem ubuntu@47.129.36.151"

monitoring:
  hosts:
    prometheus-grafana:
      ansible_host: 54.169.122.189
      prometheus_port: 9090
      grafana_port: 3000

bastion:
  hosts:
    bastion-host:
      ansible_host: 47.129.36.151
