all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_python_interpreter: /usr/bin/python3
    geth_binary_url: https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.13.14-2bd6bd01.tar.gz
    prometheus_binary_url: "https://github.com/prometheus/prometheus/releases/download/v2.48.0/prometheus-2.48.0.linux-amd64.tar.gz"

geth_nodes:
  hosts:
    geth-node-1:
      ansible_host: 10.0.1.162
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/runner/.ssh/ethereum-devops-private-key.pem
      ansible_ssh_common_args: >-
        -o ProxyCommand="ssh -i /home/runner/.ssh/ethereum-devops-private-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p ubuntu@47.129.36.151"
    geth-node-2:
      ansible_host: 10.0.1.90
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/runner/.ssh/ethereum-devops-private-key.pem
      ansible_ssh_common_args: >-
        -o ProxyCommand="ssh -i /home/runner/.ssh/ethereum-devops-private-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p ubuntu@47.129.36.151"
    geth-node-3:
      ansible_host: 10.0.3.21
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/runner/.ssh/ethereum-devops-private-key.pem
      ansible_ssh_common_args: >-
        -o ProxyCommand="ssh -i /home/runner/.ssh/ethereum-devops-private-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p ubuntu@47.129.36.151"    


monitoring:
  hosts:
    prometheus-grafana:
      ansible_host: 54.169.122.189
      prometheus_port: 9090
      grafana_port: 3000
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/runner/.ssh/ethereum-devops-private-key.pem

bastion:
  hosts:
    bastion-host:
      ansible_host: 47.129.36.151
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/runner/.ssh/ethereum-devops-private-key.pem
