---
- name: Create prometheus user
  user:
    name: "{{ prometheus_user }}"
    system: yes
    shell: /bin/false
    home: "{{ prometheus_home }}"
    create_home: yes

- name: Create prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0755'
  loop:
    - "{{ prometheus_home }}"
    - "{{ prometheus_data_dir }}"
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_config_dir }}/rules"

- name: Download and extract Prometheus
  unarchive:
    src: "{{ prometheus_binary_url }}"
    dest: /tmp
    remote_src: yes
    creates: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64"

- name: Install Prometheus binaries
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: /usr/local/bin/{{ item }}
    mode: '0755'
    owner: root
    group: root
    remote_src: yes
  loop:
    - prometheus
    - promtool

- name: Copy console files
  synchronize:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}/"
    dest: "{{ prometheus_config_dir }}/{{ item }}/"
    recursive: yes
  loop:
    - consoles
    - console_libraries
  delegate_to: "{{ inventory_hostname }}"

- name: Create Prometheus configuration
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0644'
  notify: restart prometheus

- name: Create Prometheus systemd service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: '0644'
  notify:
    - reload systemd
    - restart prometheus

- name: Start and enable Prometheus service
  systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes

- name: Wait for Prometheus to start
  wait_for:
    port: "{{ prometheus_port }}"
    host: "{{ ansible_host }}"
    delay: 10
    timeout: 60
